export const etiquetas = {
    //LOGIN
    numero_documento: 'NÚMERO DE DOCUMENTO',
    contrasena: 'CONTRASEÑA',
    login: "INGRESAR",
    messageErrorPre: 'EL CAMPO ',
    messageErrorPost: ' ES REQUERIDO',
    no_aplica: 'NO APLICA',
    //IPO
    ipo_header_one: '1. DATOS GENERALES DE LA ACTIVIDAD A REALIZAR',
    ipo_empresa_colaboradora: 'Empresa colaboradora',
    ipo_empresa_colaboradora_ing: 'INGELÉCTRICA S.A.',
    ipo_responsable_visita: 'Responsable de la visita previa o levantamiento *',
    ipo_coordinador_codensa: 'Coordinador codensa *',
    ipo_coordinador_codensa_mv: 'MARIA VICTORIA RONDON',
    ipo_proceso: 'Proceso',
    ipo_fecha_proceso: 'Fecha del proceso',
    ipo_tipo_grupo: 'Tipo de grupo técnico sugerido para la tarea',
    ipo_tipo_sector: 'Tipo sector *',
    ipo_coordenada_x: 'Coordenada X *',
    ipo_coordenada_y: 'Coordenada Y *',
    ipo_actividad: 'Actividad',
    ipo_direccion: 'Dirección *',
    ipo_localidad_barrio: 'Localidad barrio',
    ipo_hospital_cercano: 'Hospital más cercano *',
    ipo_header_two: '2. ESPECIFICACIÓN INFRAESTRUCTURA',
    ipo_nivel_tension: 'Nivel tensión *',
    ipo_tipo_trabajo: 'Tipo Trabajo *',
    ipo_tipo_red: 'Tipo red *',
    ipo_tipo_subestacion: 'Tipo subestación *',
    ipo_datos_infraestructura: 'Datos infraestructura',
    ipo_circuito: 'Circuito',
    ipo_numero_apoyo: 'Número de apoyo *',
    ipo_trabajo_lineas: 'Trabajo líneas *',
    ipo_zona: 'Zona*',
    ipo_numero_proceso_inst: 'N° proce/InsTruc',
    ipo_numero_proceso_inst_dato: 'RG01-IN296',
    ipo_header_three: '3. RESPONSABLES DE LA EJECUCIÓN DE LOS TRABAJOS',
    ipo_responsabilidad_ejecucion: 'Responsabilidad de ejecución de los trabajos',
    ipo_tipo_grupo_resp: 'Tipo Grupo',
    ipo_movil: 'Móvil',
    ipo_placa: 'Placa',
    ipo_insp_pre_veh: 'Inspc. Pre_vehículo',
    ipo_fecha_ejecucion: 'Fecha de ejecución',
    ipo_header_four: '4. IDENTIFICACIÓN DEL RIESGO VISITA PREVIA (REALIZADO RESPONSABLE LEVANTAMIENTO - PRE) / EJECUCIÓN DE TRABAJOS (REALIZADO POR EL EQUIPO DE TRABAJO - EJEC)',
    ipo_intro_riesgos: 'Seleccione \'SÍ\' o \'NO\' marcando en la casilla correspondiente al tipo de riesgo presente en la actividad que va a realizar, en caso de existir riesgo seleccione la(s) medida(s) de control para minimizar este riesgo',
    ipo_prev: 'PREV',
    ipo_ejec: 'EJEC',
    ipo_medidas_control: 'Medidas de control',
};