export const etiquetas = {
    //GLOBALES
    btn_si: 'SÍ',
    btn_no: 'NO',
    btn_aceptar: 'Aceptar',
    btn_cancelar: 'Cancelar',
    no_connection: 'No hay conexión de datos activa',
    btn_guardar: 'Guardar',
    ingelectrica: 'INGELÉCTRICA S.A.',
    //LOGIN
    numero_documento: 'NÚMERO DE DOCUMENTO',
    contrasena: 'CONTRASEÑA',
    login: "INGRESAR",
    messageErrorPre: 'EL CAMPO ',
    messageErrorPost: ' ES REQUERIDO',
    no_aplica: 'NO APLICA',
    titulo_barra: 'Datos almacenados',
    titulo_actualizar_listados: 'Actualizar listados',
    mensaje_actualizar_listados: 'Mediante esta operación usted actualizará el listado de opciones de la app desde el sistema central (requiere conexión a internet) ¿Desea continuar?',
    mensaje_actualizando: 'Actualizando datos...',
    mensaje_datos_actualizados: 'Se actualizaron los valores de los listados correctamente',
    titulo_eliminar_datos: 'Eliminar datos',
    mensaje_eliminar_datos: '¡ADVERTENCIA! Se eliminarán todos los datos almacenados en el equipo (formularios e imágenes) por lo cual se recomienda NO USAR esta opción a menos que el administrador del sistema se lo indique por detección de fallas en el archivo de datos. ¿Desea continuar?',
    mensaje_eliminando: 'Eliminando datos...',
    mensaje_datos_eliminados: 'Se han eliminado los datos del equipo',
    //IPO
    ipo_header_one: '1. DATOS GENERALES DE LA ACTIVIDAD A REALIZAR',
    ipo_empresa_colaboradora: 'Empresa colaboradora',
    ipo_empresa_colaboradora_ing: 'INGELÉCTRICA S.A.',
    ipo_responsable_visita: 'Responsable de la visita previa o levantamiento *',
    ipo_coordinador_codensa: 'Coordinador codensa *',
    ipo_coordinador_codensa_mv: 'MARIA VICTORIA RONDON',
    ipo_proceso: 'Proceso',
    ipo_fecha_proceso: 'Fecha del proceso',
    ipo_tipo_grupo: 'Tipo de grupo técnico sugerido para la tarea',
    ipo_tipo_sector: 'Tipo sector *',
    ipo_coordenada_x: 'Coordenada X *',
    ipo_coordenada_y: 'Coordenada Y *',
    ipo_actividad: 'Actividad',
    ipo_direccion: 'Dirección *',
    ipo_localidad_barrio: 'Localidad barrio',
    ipo_hospital_cercano: 'Hospital más cercano *',
    ipo_header_two: '2. ESPECIFICACIÓN INFRAESTRUCTURA',
    ipo_nivel_tension: 'Nivel tensión *',
    ipo_tipo_trabajo: 'Tipo Trabajo *',
    ipo_tipo_red: 'Tipo red *',
    ipo_tipo_subestacion: 'Tipo subestación *',
    ipo_datos_infraestructura: 'Datos infraestructura',
    ipo_circuito: 'Circuito',
    ipo_numero_apoyo: 'Número de apoyo *',
    ipo_trabajo_lineas: 'Trabajo líneas *',
    ipo_zona: 'Zona*',
    ipo_numero_proceso_inst: 'N° proce/InsTruc',
    ipo_numero_proceso_inst_dato: 'RG01-IN296',
    ipo_header_three: '3. RESPONSABLES DE LA EJECUCIÓN DE LOS TRABAJOS',
    ipo_responsabilidad_ejecucion: 'Responsabilidad de ejecución de los trabajos',
    ipo_tipo_grupo_resp: 'Tipo Grupo',
    ipo_movil: 'Móvil',
    ipo_placa: 'Placa',
    ipo_insp_pre_veh: 'Inspc. Pre_vehículo',
    ipo_fecha_ejecucion: 'Fecha de ejecución',
    ipo_header_four: '4. IDENTIFICACIÓN DEL RIESGO VISITA PREVIA (REALIZADO RESPONSABLE LEVANTAMIENTO - PRE) / EJECUCIÓN DE TRABAJOS (REALIZADO POR EL EQUIPO DE TRABAJO - EJEC)',
    ipo_intro_riesgos: 'Seleccione \'SÍ\' o \'NO\' marcando en la casilla correspondiente al tipo de riesgo presente en la actividad que va a realizar, en caso de existir riesgo seleccione la(s) medida(s) de control para minimizar este riesgo',
    ipo_prev: 'PREV',
    ipo_ejec: 'EJEC',
    ipo_medidas_control: 'Medidas de control',
    //CONSULTA
    consulta_gom: 'GOM',
    consulta_proceso: 'PROCESO',
    consulta_fecha: 'FECHA DE EJECUCIÓN',
    consulta_cuadrilla: 'CUADRILLA',
    consulta_descargo: 'DESCARGO',
    consulta_cd: 'CD',
    consulta_buscar: 'BUSCAR',
    //RG
    rg_proveedor: 'Proveedor y/o empresa colaboradora',
    rg_nombre_responsable: 'Nombre responsable',
    rg_cd_nombre: 'CD_NOMBRE_CONS_NOM_ID_TRF',
    rg_cd_nombre_enc: 'CD_NOMBRE_CONS_NOM_ID_TRF ENCONTRADO',
    rg_tipo_equipo: 'Tipo de equipo',
    rg_orden_trabajo: 'Orden de trabajo',
    rg_descargo: 'Descargo',
    rg_cantidad_placas: 'Cantidad de placas del equipo',
    rg_numero_serie: 'Número de serie en placa de fabricante',
    rg_equipo_reparado: 'Equipo reparado',
    rg_empresa_reparacion: 'Empresa que realizó la reparación',
    rg_numero_serie_reparacion: 'Número de serie en placa de reparación',
    rg_fecha_reparacion: 'Fecha de reparación del equipo',
    rg_empresa_labor: 'Empresa que realizó la labor',
    rg_municipio: 'Municipio',
    rg_localidad: 'Localidad',
    rg_bario_vereda: 'Barrio o vereda',
    rg_direccion: 'Dirección del equipo o elemento',
    rg_equipo_encontrado: 'Equipo encontrado en coordenadas entregadas',
    rg_latitud: 'Coordenadas latitud',
    rg_longitud: 'Coordenadas longitud',
    rg_requiere_gestor: 'Requiere gestor social',
    rg_descripcion_zona_riesgo: 'Descripción zona de riesgo',
    rg_codigo_zona_riesgo: 'Código zona de riesgo',
    rg_estado_equipo: 'Estado del equipo',
    rg_marca_transformador: 'Marca del transformador',
    rg_pais_fabricacion: 'País de fabricación',
    rg_potencia_kva: 'Potencia KVA',
    rg_anio_fabricacion: 'Año de fabricación',
    rg_cuadrilla_placa: 'N° de cuadrila/Placa del vehículo',
    rg_marcacion_encontrada: 'Marcación encontrada',
    rg_ideam: 'Ideam (placa verde)',
    rg_serie_placa: 'Serie (placa blanca)',
    rg_hermeticamente_sellado: 'Herméticamente sellado',
    rg_tipo_aislamiento: 'Tpo aislamiento',
    rg_observaciones: 'Observaciones',
    rg_viable: 'Viable',
    rg_causa: 'Causa',
    rg_causas_tecnicas: 'Causas técnicas',
    rg_observaciones_causa: 'Observaciones sobre causa',
    rg_agregar_fotos_rg: 'Agregar fotos RG',
    rg_agregar_fotos_pc: 'Agregar fotos placas',
    rg_titulo_dialogo_fotos: 'Agregar fotos',
    rg_mensaje_dialogo_fotos: 'Seleccione la fuente de las imágenes',
    rg_fotos_camara: 'Cámara',
    rg_fotos_galeria: 'Galería',
    rg_fotos_permiso_denegado: 'Se ha denegado el permiso de la app al acceso a la cámara',
    //PLANILLA DE TRABAJO
    pt_cant: 'Cantidad',
    pt_actividad: 'Actividad',
    pt_descripcion_actividad: 'Descripción de la actividad',
    pt_agregar_nodo: 'Agregar nodo',
    pt_eliminar_nodo: 'Eliminar nodo',
    pt_error_agregar_nodo: 'Debe diligenciar todos los campos para agregar otro nodo',
    //SINCRONIZACIÓN
    sinc_datos_ok: 'Se han sincronizado los datos correctamente, las imágenes se cargarán en segundo plano',
    sinc_datos_err: 'Error durante la sincronización de datos',
    sinc_error_ejec: 'Hay un error durante la ejecución de sincronización, verifique su conexión y si es correcta, por favor reporte al adminsitrador del sistema',
    sinc_no_conexion: 'No se ha detectado una conexión estable, por favor verifique e intente nuevamente'
};